"""Emit frontend/src/styles/deck.css from tokens.css + deck.css, scoped to .deck.

Landing Deck unscoped would repaint the live app: --ok/--warn/--err exist in both
token files with different values, .dim is used 21 times already, and deck.css
restyles body/button/scrollbars globally. Scoping makes it opt-in per surface —
a page joins Deck by carrying className="deck".

Run after editing the design files:  python3 build_app_css.py
"""

import pathlib
import re

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent.parent / "frontend" / "src" / "styles" / "deck.css"

# Selectors that would otherwise apply to the whole document.
#
# Element resets are scoped through `:where(.deck)`, which contributes no
# specificity, so they land at (0,0,1) and stay *below* the component classes.
# Written as a plain `.deck button` they are (0,1,1) and beat `.dk-btn` (0,1,0)
# — which silently stripped the padding, border and background from every
# button in the design system.
GLOBAL = {
    "* ": ":where(.deck) *, .deck ",
    "html, body ": None,  # the app owns these
    "body ": ".deck ",
    "button, input ": ":where(.deck) button, :where(.deck) input ",
    "button ": ":where(.deck) button ",
    "a ": ":where(.deck) a ",
    ":focus-visible ": ".deck :focus-visible ",
    "::-webkit-scrollbar ": ":where(.deck) ::-webkit-scrollbar ",
    "::-webkit-scrollbar-track ": ":where(.deck) ::-webkit-scrollbar-track ",
    "::-webkit-scrollbar-thumb ": ":where(.deck) ::-webkit-scrollbar-thumb ",
    "::-webkit-scrollbar-thumb:hover ": ":where(.deck) ::-webkit-scrollbar-thumb:hover ",
    ":root ": ".deck ",
    ".sans ": ".deck .sans ",
    ".dim ": ".deck .dim ",
    ".trunc ": ".deck .trunc ",
    ".mono ": ".deck .mono ",
    ".tnum ": ".deck .tnum ",
    ".sr ": ".deck .sr ",
}
ATTR = re.compile(r'^\[data-(theme|colour|density)="([a-z]+)"\] $')


def scope(src: str) -> list[str]:
    out, skip = [], False
    for line in src.splitlines():
        head = re.match(r"^([^{]+)\{", line)
        if skip:
            out.append(line)
            if "}" in line:
                skip = False
            continue
        if head:
            sel = head.group(1)
            key = sel if sel.endswith(" ") else sel + " "
            if key in GLOBAL:
                repl = GLOBAL[key]
                if repl is None:  # dropped: let the app keep owning it
                    skip = "}" not in line
                    continue
                line = line.replace(sel, repl, 1)
            elif ATTR.match(key):
                line = line.replace(sel.rstrip(), sel.rstrip() + " .deck", 1)
        out.append(line)
    return out


parts = [
    "/* Generated by design/deck/build_app_css.py — do not edit. */",
    "/* Everything is scoped to .deck so it cannot touch the old theme. */",
]
for name in ("tokens.css", "deck.css"):
    parts.append(f"\n/* ---- {name} ---- */")
    parts += scope((HERE / name).read_text())

OUT.write_text("\n".join(parts) + "\n")
print(f"wrote {OUT.relative_to(HERE.parent.parent)} ({len(parts)} lines)")
