"""Response shapes for the effective-hooks read.

Kept out of ``app/models/hooks.py`` on purpose. That module holds the shapes of
the *setup* flow — is the user's settings.json wired to this app, did the probe
come back — and every field in it is a verdict about this app's own hooks. The
shapes here describe somebody else's hooks as much as ours, and carry the
redaction rule that goes with that, so they are worth reading as their own
group rather than as four more classes in a file about onboarding.

``app/services/effective_hooks_service.py`` returns plain dicts and the router
wraps them into these models on the way out, the pattern already used for
``HookVerifyReport``.

Two things are absent from these models by decision, not omission:

* **No measured duration, anywhere.** Not per hook, not per event, not as an
  aggregate. Hook payloads carry no timing and a transcript can only time this
  app's own hook, so any number here would describe one contributor out of
  eight while looking like it described the event. Real per-hook timing needs
  the harness to emit it, and that is a later phase. ``timeout_seconds`` is the
  declared ceiling read out of the config file — a configured value, never an
  observation.
* **No third-party command string.** ``command`` is populated only for hooks
  this app itself generated, and "generated by us" means the string is exactly
  one the app's own hook builder emits — not merely a command that mentions one
  of our ingest URLs, which is a thing somebody else's command can do and a
  hostile one has reason to. For every other hook ``command`` is ``None`` and
  ``executable`` is all there is: a bare program name for a command hook, and
  for an ``http`` hook the host and port with any ``user:password@`` prefix
  dropped along with the path and query. A hook command is an arbitrary shell
  string that can carry a token in its argv, and this response reaches the
  frontend and every log on the way.
"""

from __future__ import annotations

from pydantic import BaseModel


class EffectiveHookSource(BaseModel):
    """One of the eight places a hook on an event can come from.

    ``observable`` is false for exactly one source — a settings file named on
    the command line, whose path this app never sees. It is listed anyway so
    that its absence from the counts is stated rather than implied.
    """

    slug: str
    label: str
    where: str
    observable: bool
    note: str


class EffectiveHookContribution(BaseModel):
    """One hook, as one file declares it, on one event.

    ``command`` is the full command and is present only when
    ``codenest_authored`` is true — which holds only for a string equal to one
    the app's own builder mints. Otherwise it is ``None``, ``redacted`` is
    true, and ``executable`` is the whole of what this reports about what runs:
    a program name with every argument discarded, or, for an ``http`` hook, a
    host and port with no credential, path or query left in it.
    """

    event: str
    source: str
    origin: str
    matcher: str | None = None
    hook_type: str
    executable: str
    command: str | None = None
    redacted: bool
    codenest_authored: bool
    # The timeout the file declares, in seconds. A configured ceiling, not a
    # measurement — see the module docstring.
    timeout_seconds: int | None = None


class EffectiveHookSourceBucket(BaseModel):
    """What one source contributes to one event.

    A bucket is emitted for all eight sources on every event, including the
    empty ones: "nothing here" is an answer the reader asked for, and a bucket
    that vanished when it was empty would make an event look like it had fewer
    possible origins than it has.
    """

    source: str
    label: str
    observable: bool
    count: int
    contributions: list[EffectiveHookContribution] = []


class EffectiveHookEvent(BaseModel):
    """One hook event and everything found on it.

    ``total`` is the sum across all eight buckets and is the number this whole
    read exists to produce: how many separate programs sit on this event's
    critical path. It is a sum because hooks accumulate — each source adds to
    what the others declared, and every hook found is a hook that runs.
    """

    event: str
    tier: str
    ingest_path: str
    total: int
    by_source: list[EffectiveHookSourceBucket] = []


class EffectiveHookScannedFile(BaseModel):
    """One file the scan tried to read, and how that went.

    Reported per file rather than collapsed into a single status because "your
    project settings file is not valid JSON" and "you have no project settings
    file" produce the same empty event list and mean completely different
    things.
    """

    source: str
    path: str
    # "ok" | "missing_file" | "invalid_json" | "unreadable" | "out_of_scope"
    # | "truncated"
    status: str
    detail: str | None = None


class EffectiveHooksReport(BaseModel):
    """Response for ``POST /api/v1/workspace/hooks/effective``."""

    base_url: str
    sources: list[EffectiveHookSource]
    scanned: list[EffectiveHookScannedFile] = []
    events: list[EffectiveHookEvent] = []
